config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "gardens#index"
  resources :gardens do
    resources :plants, only: [:new, :create]
  end
  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  BIO = %w[desert jungle winter volcano]
  has_many :plants, dependent: :destroy

  validates :name, :city, :bio, :image_url, presence: true
  validates :bio, inclusion: {in: BIO}

end

app/models/plant.rb
class Plant < ApplicationRecord

  SIZE = %w[small medium large]
  belongs_to :garden

  validates :name, :size, :image_url, presence: true
  validates :size, inclusion: {in: SIZE}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show]
  def index
    @gardens = Garden.all

  end

  def show
  end

  def new
    @garden = Garden.new
  end

  def create
    @garden = Garden.new(garden_params)
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name, :city, :bio, :image_url)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_garden

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end


  private

  def set_garden
    @garden = Garden.find(params[:garden_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :size, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/index.html.erb
<% @gardens.each do |g| %>
  <h4>
    <%= link_to "#{g.name}", garden_path(g) %>
  </h4>
<% end %>
<%= link_to 'new', new_garden_path  %>

app/views/gardens/new.html.erb
<div class="container">
  <%= simple_form_for @garden do |f| %>
    <%= f.input :name %>
    <%= f.input :city %>
    <%= f.input :bio, collection: Garden::BIO %>
    <%= f.input :image_url %>
    <%= f.button :submit %>
  <% end %>
  <%= link_to 'back home', gardens_path  %>
</div>

app/views/gardens/show.html.erb
<h2><%= @garden.name %></h2>
<p><%= @garden.city %></p>
<p><%= @garden.bio%></p>
<%= image_tag @garden.image_url, alt: "garden photo" %>
<%= link_to "Add plant", new_garden_plant_path(@garden)  %>
<% @garden.plants.each do |plant| %>
  <p> <%= plant.name %></p>
  <p> <%= plant.size %></p>
  <%= image_tag plant.image_url, alt: "plant pic" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<div class="container">
  <%= simple_form_for [@garden, @plant] do |f| %>
    <%= f.input :name %>
    <%= f.input :size, collection: Plant::SIZE %>
    <%= f.input :image_url %>
    <%= f.button :submit %>
  <% end %>
</div>